development:
  access_key_id: 16T5A5YZ6GTZKQQE3982
  secret_access_key: GJRY4vFqy7NfdnuDA77VzWvc4PhxKn94AbpTDhhL
  bucket: asb-criterion-template-videos
production:
  access_key_id: 16T5A5YZ6GTZKQQE3982
  secret_access_key: GJRY4vFqy7NfdnuDA77VzWvc4PhxKn94AbpTDhhL
  bucket: asb-criterion-template-videos
